route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email_notifications'

receivers:
  - name: 'email_notifications'
    email_configs:
      - to: 'pbb8112002@gmail.com'
        from: 'pbb8112002@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'pbb8112002@gmail.com'
        auth_password: 'fsnc qzep jwew qygt'
        require_tls: true
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname']
